# =====================
# Python 3.10 core image
# ---------------------

FROM docker.uclv.cu/python:3.10-slim

# =====================
# Basic enviroment setup
# ---------------------

RUN apt update \
  && apt install -y \
  curl \
  locales \
  nano \
  ssh \
  sudo \
  bash \
  git \
  make \
  gcc \
  build-essential \ 
  python3-dev


# =====================
# User stuff
# ---------------------

# https://wiki.debian.org/Locale#Manually
RUN sed -i "s/# en_US.UTF-8/en_US.UTF-8/" /etc/locale.gen \
  && locale-gen
ENV LANG=en_US.UTF-8
RUN chsh -s /bin/bash
ENV SHELL=/bin/bash
RUN adduser --gecos '' --disabled-password coder && \
  echo "coder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/nopasswd


# ==========================================
# Poetry related config
# ------------------------------------------
ARG PIPX_VERSION=1.2.0 POETRY_VERSION=1.3.1
ENV PATH=/opt/pipx/bin:/app/.venv/bin:$PATH PIPX_BIN_DIR=/opt/pipx/bin PIPX_HOME=/opt/pipx/home POETRY_VIRTUALENVS_IN_PROJECT=true

# ==========================================
# Project-specific installation instruction
# ------------------------------------------

COPY bash.bashrc /etc
RUN chmod +x /etc/bash.bashrc
ENV BUILD_ENVIRONMENT="development"
# ENV XDG_CACHE_HOME="/opt/dev/cache"
WORKDIR /home/coder/autogoal



# Make RUN commands use the autogoal environment
COPY makefile /home/coder/autogoal/

# Setup poetry configuration
# RUN pip install -U pip setuptools
# RUN pip install poetry==1.3.1
# RUN pip install -U pip virtualenv
# RUN poetry config virtualenvs.create false --local

SHELL ["/bin/bash", "-c"]
USER coder
RUN sudo mkdir -p /home/coder/autogoal/data && sudo chown coder:coder /home/coder/autogoal
VOLUME /home/coder/autogoal
RUN sudo rm -rf /home/coder/autogoal/storage
RUN sudo chown -R coder /home/coder

# Copy code-base for autogoal-core
COPY autogoal /home/coder/autogoal/autogoal

RUN python -m pip install --no-cache-dir --upgrade --user pip "pipx==$PIPX_VERSION"
# RUN python -m pipx ensurepath
# RUN python -m pipx completions
RUN pipx install "poetry==$POETRY_VERSION"
# Copy code-base for autogoal-contrib
COPY autogoal-contrib /home/coder/autogoal/autogoal-contrib

# Copy code-base for autogoal-remote
COPY autogoal-remote /home/coder/autogoal/autogoal-remote

# Install autogoal core
COPY dockerfiles/install-package.sh install-package.sh 
RUN ./install-package.sh core

CMD ["/bin/bash"]